### PR TITLE
Rename tags to appendTags for Push command

### PR DESCRIPTION
**Pull request by stelabouras**
Renames tags to appendTags for Push command to conform to the naming
style of the rest of the CLI apps.

### CODE REVIEW

**Comment by stelabouras** [comment]
Note regarding tests: 

Unfortunately it looks like unit tests for CLI commands are a pain to implement.

There's no official documentation for writing unit tests using Swift Argument Parser library and the only post I could find (https://forums.swift.org/t/unit-testing-argument-parsing/47933/3) didn't work for me.

On top of that, in order to be able to test whether the final strings that are going to be pushed contain the appended tags, we would either need to implement a mock server (like the Java CLI does) which cannot be easily done (possibly with swizzling) or by writing the whole command log to a file and then reading from it.

**Review by dbendilas — COMMENTED** [review]
When using the CLI, how should it be called, `append-tags` or `--appendTags`? The former is what we need.

**Comment by stelabouras** [comment]
> When using the CLI, how should it be called, `append-tags` or `--appendTags`? The former is what we need.

Camel-case properties are automatically transformed using the `-` character as a word separator so `appendTags` becomes `--append-tags`.

**Review by dbendilas — APPROVED** [review]
👍 
Please rebase if the other PR is merged first and ping me to approve again

**Pull request merged**
